language: go
sudo: required

go:
- 1.12

env:
  global:
  - GO111MODULE=on
  - OC_BINARY_URL=http://mirror.openshift.com/pub/openshift-v4/clients/oc/4.2/linux/oc.tar.gz
  - KUBE_VERSION=v1.14.2
  - KUBE_BINARY=https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl

before_install:
# Install helm
- curl -L https://git.io/get_helm.sh | bash
# Install kubectl
- curl -LO ${KUBE_BINARY} && chmod +x ./kubectl && sudo mv ./kubectl /bin/kubectl
# Install oc
- sudo wget -qO- ${OC_BINARY_URL} | sudo tar -xvz -C /bin
# Install minikube
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
- sudo chmod +x minikube && sudo mv minikube /usr/local/bin/
- sudo minikube start --vm-driver=none --kubernetes-version=${KUBE_VERSION}
- sudo minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
